# -*- coding: utf-8 -*-
"""C2 - SEM 15 - IN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vktT7GxbvcGnBzvzeHF1KL0AK3emXnZi

# Análisis de Datos — Integratel Perú
### Proyecto de Analítica de Negocios — Inteligencia de Negocios

**Docente:** Mg. Max Alonzo Huaman – Ing. Yan Casayco Contreras
---
**INTEGRANTES:**
- Cortez Ponce Brianna Shaquel

- Cueva Ricse Alex Roberto

- Guevara Chamorro Augusto Jose

- Ore Campos Josef Pablo

- Porras Veli Ricardo

**Contenido:**
1. Instalación y carga de datos
2. Carga del Data Warehouse

## 1. Instalación de librerías y carga de datos
"""

# @title Dependencias necesarias
# Este bloque instala y carga las librerías fundamentales para el análisis de datos.
# Es crucial para la fase de Preparación de Datos de CRISP-DM, ya que habilita las herramientas
# necesarias para manipular, limpiar y visualizar los datos de Integratel Perú, sentando las bases
# para todas las fases posteriores del proyecto.
!pip install plotly openpyxl kaleido -q

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

"""## 2. Carga del Data Warehouse"""

# @title 2.1 Carga del Data Warehouse de Integratel (DIM y FACT tables)
# Este código gestiona la carga inicial del Data Warehouse de Integratel desde un archivo Excel.
# Es vital en la fase de Comprensión de los Datos y Preparación de CRISP-DM,
# al disponibilizar los datos brutos de la empresa para su posterior análisis,
# incluyendo información clave para la identificación del churn.
# ─────────────────────────────────────────────────────────────────────────────
# CARGA DEL DATASET
# ─────────────────────────────────────────────────────────────────────────────

import pandas as pd
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]

xl = pd.ExcelFile(filename)

# Cargar todas las tablas
dim_tiempo    = pd.read_excel(xl, "DIM_TIEMPO")
dim_cliente   = pd.read_excel(xl, "DIM_CLIENTE")
dim_producto  = pd.read_excel(xl, "DIM_PRODUCTO")
dim_nodo      = pd.read_excel(xl, "DIM_NODO_RED")
dim_empleado  = pd.read_excel(xl, "DIM_EMPLEADO")
fact_fact     = pd.read_excel(xl, "FACT_FACTURACION")
fact_av       = pd.read_excel(xl, "FACT_AVERIAS")
fact_churn    = pd.read_excel(xl, "FACT_CHURN")
fact_red      = pd.read_excel(xl, "FACT_USO_RED")

# Derivar columna año en averias y churn
fact_av["año"]    = fact_av["id_tiempo"].astype(str).str[:4].astype(int)
fact_churn["año"] = fact_churn["id_tiempo"].astype(str).str[:4].astype(int)

print(f"   DIM_TIEMPO      : {len(dim_tiempo):>7,} registros")
print(f"   DIM_CLIENTE      : {len(dim_cliente):>7,} registros")
print(f"   DIM_PRODUCTO     : {len(dim_producto):>7,} registros")
print(f"   DIM_NODO_RED     : {len(dim_nodo):>7,} registros")
print(f"   DIM_EMPLEADO     : {len(dim_empleado):>7,} registros")
print(f"   FACT_FACTURACION : {len(fact_fact):>7,} registros")
print(f"   FACT_AVERIAS     : {len(fact_av):>7,} registros")
print(f"   FACT_CHURN       : {len(fact_churn):>7,} registros")
print(f"   FACT_USO_RED     : {len(fact_red):>7,} registros")

# @title 2.2 Construcción de Tabla Comparativa de KPIs Anuales
# Este segmento calcula y presenta KPIs anuales clave para Integratel Perú, como ARPU, ingresos y churn.
# Pertenece a la fase de Comprensión de los Datos de CRISP-DM, ofreciendo una visión macro
# del rendimiento del negocio. Permite identificar tendencias y áreas críticas,
# informando la estrategia para la retención de clientes y la mejora operativa.
# TABLA COMPARATIVA DE INDICADORES CLAVE

import numpy as np

# Crear diccionario base
data = {
    "Indicador": [
        "ARPU promedio (S/.)",
        "Ingresos totales muestra (S/.)",
        "Eventos de churn",
        "MTTR promedio (min)",
        "Utilización de red (%)",
        "Satisfacción cliente (1-10)"
    ]
}

# Años a analizar
years_to_analyze = [2020, 2021, 2022, 2023, 2024]
churn_anual = (
    fact_churn[
        fact_churn["año"].between(2020, 2024)
    ]
    .groupby("año")
    .size()
    .reset_index(name="bajas")
)

# Llenar columnas por año
for year in years_to_analyze:

    # Obtener métricas
    arpu = fact_churn[fact_churn["año"] == year]["arpu_promedio_sol"].mean()

    ingresos = fact_fact[fact_fact["año"] == year]["total_sol"].sum()

    bajas_df = churn_anual[churn_anual["año"] == year]

    bajas = bajas_df["bajas"].iloc[0] if not bajas_df.empty else np.nan

    mttr = fact_av[fact_av["año"] == year]["mttr_minutos"].mean()

    utilizacion = fact_red.loc[
    fact_red["año"] == year,
    "utilizacion_pct"
    ].mean()

    satisfaccion = fact_av[fact_av["año"] == year]["satisfaccion_1_10"].mean()

    # Guardar
    data[str(year)] = [
        arpu,
        ingresos,
        bajas,
        mttr,
        utilizacion,
        satisfaccion
    ]

# Crear DataFrame
tabla = pd.DataFrame(data)

# Redondear números
for col in ["2020", "2021", "2022", "2023", "2024"]:
    tabla[col] = tabla[col].astype(float).round(2)

# ─ CALCULAR VARIACIÓN DE FORMA SEGURA

variaciones = []

for i in range(len(tabla)):

    valor_2020 = tabla.loc[i, "2020"]
    valor_2024 = tabla.loc[i, "2024"]

    # Validar división
    if pd.isna(valor_2020) or valor_2020 == 0:
        variaciones.append("N/A")
    else:
        var = ((valor_2024 - valor_2020) / valor_2020) * 100
        variaciones.append(f"{var:.1f}%")

tabla["Variación"] = variaciones

# Mostrar tabla
display(tabla)

# @title 2.3 Construcción del Dataset Analítico para el Modelo
# Este código construye el dataset analítico unificando datos de averías, facturación y cliente.
# Es fundamental en la fase de Preparación de Datos de CRISP-DM,
# ya que crea una vista integral de cada cliente. Esta consolidación es crítica para Integratel Perú
# para desarrollar modelos predictivos de churn y entender el comportamiento del cliente.
# ============================================================
# CONSTRUCCIÓN DEL DATASET ANALÍTICO
# ============================================================

# Información de averías por cliente

av_cl = (
    fact_av
    .groupby("id_cliente")
    .agg(
        num_reclamos=("genero_reclamo","sum"),
        mttr_prom=("mttr_minutos","mean"),
        sat_media=("satisfaccion_1_10","mean"),
        total_averias=("id_cliente","count")
    )
    .reset_index()
)

# Información de facturación

ff_cl = (
    fact_fact
    .groupby("id_cliente")
    .agg(
        arpu=("total_sol","mean"),

        pct_venc=(
            "dias_atraso",
            lambda x:(x>0).mean()*100
        ),

        deuda_promedio=("dias_atraso","mean"),

        max_dias_atraso=("dias_atraso","max")
    )
    .reset_index()
)

# Dataset final

df_model = (

    dim_cliente[
        [
            "id_cliente",
            "segmento",
            "departamento",
            "antiguedad_meses"
        ]
    ]

    .merge(
        av_cl,
        on="id_cliente",
        how="left"
    )

    .merge(
        ff_cl,
        on="id_cliente",
        how="left"
    )

)

print(df_model.shape)

display(df_model.head())

# @title 2.4 Definición de la Variable Objetivo (Churn)
# Este código define la variable objetivo 'churn' en el dataset, codificando el estado del cliente como 0 o 1.
# Es una fase crítica en la Preparación de Datos de CRISP-DM, ya que transforma el concepto de abandono
# del cliente de Integratel Perú en una métrica binaria, esencial para el entrenamiento de modelos predictivos.
# ============================================================
# VARIABLE OBJETIVO (CHURN)
# ============================================================

df_model = df_model.merge(
    dim_cliente[
        ["id_cliente","estado_actual"]
    ],
    on="id_cliente",
    how="left"
)

df_model["churn"] = df_model["estado_actual"].map({
    "Activo":0,
    "Suspendido":0,
    "Baja":1
})

df_model.drop(columns="estado_actual", inplace=True)

# @title 2.5 Identificación de Valores Nulos
# Este código identifica la presencia y cantidad de valores nulos en el dataset analítico.
# Es una etapa clave en la Preparación de Datos de CRISP-DM, ya que el conocimiento de estos nulos
# es fundamental para Integratel Perú. Permite evaluar la calidad de los datos y planificar
# las estrategias de limpieza para garantizar la fiabilidad del modelo de churn.
# ============================================================
# VALORES NULOS
# ============================================================

print("="*70)
print("VALORES NULOS")
print("="*70)

nulos = df_model.isnull().sum()

display(nulos[nulos>0])

# @title 2.6 Tratamiento de Valores Nulos (Eliminación de Filas)
# Este bloque evalúa y ejecuta la eliminación de filas con valores nulos del dataset.
# Pertenece a la fase de Preparación de Datos de CRISP-DM, garantizando que Integratel Perú
# use únicamente registros completos y consistentes. Esto es crucial para la solidez
# y la interpretabilidad del modelo de predicción de churn.
# ============================================================
# ANÁLISIS Y ELIMINACIÓN DE FILAS CON VALORES NULOS
# ============================================================

filas_antes = len(df_model)
filas_despues = len(df_model.dropna())
filas_eliminadas = filas_antes - filas_despues
porcentaje = (filas_eliminadas / filas_antes) * 100

print("="*70)
print("ANÁLISIS DE ELIMINACIÓN DE FILAS")
print("="*70)
print(f"Filas antes: {filas_antes}")
print(f"Filas después de dropna(): {filas_despues}")
print(f"Filas eliminadas: {filas_eliminadas}")
print(f"Porcentaje eliminado: {porcentaje:.2f}%")

# ============================================================
# ELIMINACIÓN DE LAS FILAS CON VALORES NULOS
# ============================================================

df_model = df_model.dropna()

print("\n" + "="*70)
print("VERIFICACIÓN")
print("="*70)
print(f"Filas finales: {len(df_model)}")
print(f"Valores nulos restantes: {df_model.isnull().sum().sum()}")

# @title 2.7 Análisis de la Distribución de la Variable Objetivo (Churn)
# Este código analiza la distribución de la variable objetivo 'churn' en el dataset.
# Parte de las fases de Comprensión y Preparación de Datos de CRISP-DM,
# es crucial para Integratel Perú. Permite entender la proporción de clientes que abandonan,
# lo que es vital para manejar el desbalance de clases y garantizar la fiabilidad del modelo.
print("="*60)
print("Distribución de la variable objetivo")
print("="*60)

print(df_model["churn"].value_counts())

print()

print(df_model["churn"].value_counts(normalize=True)*100)

# @title 2.8 Visualización del Dataset Analítico Final
# Este código muestra las primeras filas del dataset analítico final.
# Representa una revisión final en la fase de Preparación de Datos de CRISP-DM.
# Para Integratel Perú, es una verificación visual rápida para asegurar que la estructura
# y los datos están correctos antes de avanzar al modelado, confirmando su idoneidad para el entrenamiento.
display(df_model.head())

# @title 2.9 Comparación de Características por Estado de Churn
# Este código compara las medias de características clave entre clientes con y sin churn.
# Corresponde a la fase de Comprensión de los Datos de CRISP-DM,
# ofreciendo a Integratel Perú una visión crucial sobre los factores que impulsan el abandono.
# Permite identificar atributos de clientes que se correlacionan fuertemente con el churn.
df_model.groupby("churn")[
    [
        "num_reclamos",
        "mttr_prom",
        "sat_media",
        "arpu",
        "pct_venc",
        "deuda_promedio",
        "antiguedad_meses"
    ]
].mean().round(2)

# @title 3.1 Modelo Predictivo de Churn con XGBoost
# Este bloque construye y evalúa un modelo de clasificación XGBoost para predecir el churn.
# Central en las fases de Modelado y Evaluación de CRISP-DM, este código es la base para Integratel Perú
# para identificar clientes en riesgo de abandono. Permite implementar estrategias de retención proactivas,
# optimizando los recursos y mejorando la lealtad del cliente.
# ─────────────────────────────────────────────────────────────
# MODELO PREDICTIVO DE CHURN — XGBOOST
# Integratel Perú | 2020–2024
# ─────────────────────────────────────────────────────────────

!pip install xgboost imbalanced-learn -q

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    roc_curve
)

import pandas as pd
import numpy as np

# ─────────────────────────────────────────────────────────────
# DATASET ANALÍTICO
# ─────────────────────────────────────────────────────────────

av_cl = (
    fact_av
    .groupby("id_cliente")
    .agg(
        num_reclamos=("genero_reclamo", "sum"),
        mttr_prom=("mttr_minutos", "mean"),
        sat_media=("satisfaccion_1_10", "mean"),
        total_averias=("id_cliente", "count")
    )
    .reset_index()
)

ff_cl = (
    fact_fact
    .groupby("id_cliente")
    .agg(
        arpu=("total_sol", "mean"),

        pct_venc=(
            "dias_atraso",
            lambda x: (x > 0).mean() * 100
        ),

        deuda_promedio=("dias_atraso", "mean"),
        max_dias_atraso=("dias_atraso", "max")
    )
    .reset_index()
)

df_model = (
    dim_cliente[
        [
            "id_cliente",
            "segmento",
            "departamento",
            "antiguedad_meses"
        ]
    ]

    .merge(
        av_cl,
        on="id_cliente",
        how="left"
    )

    .merge(
        ff_cl,
        on="id_cliente",
        how="left"
    )
)

# ─────────────────────────────────────────────────────────────
# VARIABLE OBJETIVO
# ─────────────────────────────────────────────────────────────

df_model["churn"] = (
    dim_cliente
    .set_index("id_cliente")["estado_actual"]
    .map({
        "Baja": 1,
        "Activo": 0,
        "Suspendido": 0
    })
    .values
)

# ─────────────────────────────────────────────────────────────
# LIMPIEZA
# ─────────────────────────────────────────────────────────────

df_model = df_model.dropna(subset=["churn"])

df_model = df_model.fillna(0)

df_model["mttr_prom"] = (
    df_model["mttr_prom"]
    .clip(0, 500)
)

df_model["pct_venc"] = (
    df_model["pct_venc"]
    .clip(0, 100)
)

# ─────────────────────────────────────────────────────────────
# ENCODING
# ─────────────────────────────────────────────────────────────

le_seg = LabelEncoder()

le_dep = LabelEncoder()

df_model["seg_enc"] = (
    le_seg.fit_transform(df_model["segmento"])
)

df_model["dep_enc"] = (
    le_dep.fit_transform(df_model["departamento"])
)

# ─────────────────────────────────────────────────────────────
# VARIABLES DEL MODELO
# ─────────────────────────────────────────────────────────────

features = [
    "antiguedad_meses",
    "num_reclamos",
    "mttr_prom",
    "sat_media",
    "total_averias",
    "arpu",
    "pct_venc",
    "deuda_promedio",
    "max_dias_atraso",
    "seg_enc",
    "dep_enc"
]

X = df_model[features]

y = df_model["churn"]

# ─────────────────────────────────────────────────────────────
# INFORMACIÓN GENERAL
# ─────────────────────────────────────────────────────────────

print("="*70)
print("DATASET DEL MODELO")
print("="*70)

print("Total clientes:", len(df_model))

print(
    "Tasa de churn:",
    round(y.mean() * 100, 2),
    "%"
)

# ─────────────────────────────────────────────────────────────
# TRAIN / TEST
# ─────────────────────────────────────────────────────────────

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.30,

    random_state=42,

    stratify=y
)

# ─────────────────────────────────────────────────────────────
# SMOTE SOLO EN TRAIN
# ─────────────────────────────────────────────────────────────

smote = SMOTE(
    random_state=42
)

X_train_res, y_train_res = smote.fit_resample(
    X_train,
    y_train
)

# ─────────────────────────────────────────────────────────────
# MODELO XGBOOST
# ─────────────────────────────────────────────────────────────

clf = XGBClassifier(
    objective="binary:logistic",
    eval_metric="auc",
    n_estimators=120,
    max_depth=3,
    learning_rate=0.03,
    subsample=0.70,
    colsample_bytree=0.70,
    reg_alpha=2,
    reg_lambda=4,
    min_child_weight=8,
    gamma=1,
    random_state=42
)

# ─────────────────────────────────────────────────────────────
# ENTRENAMIENTO
# ─────────────────────────────────────────────────────────────

clf.fit(
    X_train_res,
    y_train_res
)

# ─────────────────────────────────────────────────────────────
# PREDICCIÓN
# ─────────────────────────────────────────────────────────────

y_prob = clf.predict_proba(X_test)[:,1]

threshold = 0.60

y_pred = (
    y_prob >= threshold
).astype(int)

# ─────────────────────────────────────────────────────────────
# MÉTRICAS
# ─────────────────────────────────────────────────────────────

auc = roc_auc_score(
    y_test,
    y_prob
)

print("\n" + "="*70)
print("RESULTADOS DEL MODELO")
print("="*70)

print(
    "AUC:",
    round(auc, 4)
)

print(
    "\nThreshold:",
    threshold
)

print("\nREPORTE DE CLASIFICACIÓN\n")

print(
    classification_report(
        y_test,
        y_pred
    )
)

# @title 4.1 Simulador Interactivo de Predicción de Churn
# Este simulador interactivo permite predecir el churn para clientes individuales en tiempo real.
# Corresponde a la fase de Despliegue de CRISP-DM, brindando a Integratel Perú una herramienta práctica
# para que los usuarios de negocio evalúen el riesgo de abandono de cada cliente,
# facilitando la toma de decisiones informadas para estrategias de retención personalizadas.
print("="*70)
print("   SIMULADOR PREDICTIVO DE CHURN")
print("="*70)

# =========================
# INPUTS
# =========================

antiguedad = float(input("Antigüedad (meses): "))
reclamos = int(input("Número de reclamos: "))
mttr = float(input("MTTR promedio (min): "))
sat = float(input("Satisfacción (1-10): "))
arpu = float(input("ARPU promedio: "))
pct_venc = float(input("% facturas vencidas: "))
averias = int(input("Total averías: "))
deuda = float(input("Deuda promedio: "))
max_atraso = float(input("Máx días de atraso: "))

print("\nSegmento disponible:", list(le_seg.classes_))
segmento = input("Segmento: ")
seg_enc = le_seg.transform([segmento])[0]

print("\nDepartamento disponible:", list(le_dep.classes_))
departamento = input("Departamento: ")
dep_enc = le_dep.transform([departamento])[0]

# =========================
# DATAFRAME CORRECTO
# =========================

cliente = pd.DataFrame([{
    "antiguedad_meses": antiguedad,
    "num_reclamos": reclamos,
    "mttr_prom": mttr,
    "sat_media": sat,
    "total_averias": averias,
    "arpu": arpu,
    "pct_venc": pct_venc,
    "deuda_promedio": deuda,
    "max_dias_atraso": max_atraso,
    "seg_enc": seg_enc,
    "dep_enc": dep_enc
}])

# =========================
# PREDICCIÓN
# =========================

prob_ml = clf.predict_proba(cliente)[0][1]

threshold = 0.60
pred = int(prob_ml >= threshold)

estado = "CHURN" if pred == 1 else "ACTIVO"

# =========================
# RIESGO
# =========================

if prob_ml >= 0.70:
    riesgo = "ALTO"
elif prob_ml >= 0.40:
    riesgo = "MEDIO"
else:
    riesgo = "BAJO"

# =========================
# RESULTADO
# =========================

print("\n" + "="*70)
print("RESULTADO DEL MODELO")
print("="*70)

print("Estado:", estado)
print("Probabilidad:", round(prob_ml * 100, 2), "%")
print("Riesgo:", riesgo)

# =========================
# FACTORES
# =========================

print("\nFACTORES DETECTADOS:")

factores = []

if reclamos >= 5:
    factores.append("Muchos reclamos")

if mttr >= 300:
    factores.append("MTTR alto")

if sat <= 3:
    factores.append("Baja satisfacción")

if pct_venc >= 50:
    factores.append("Alta morosidad")

if averias >= 5:
    factores.append("Muchas averías")

if len(factores) == 0:
    print("• Sin factores críticos")
else:
    for f in factores:
        print("•", f)

# =========================
# RECOMENDACIÓN
# =========================

print("\nRECOMENDACIÓN:")

if prob_ml >= 0.70:
    print("Acción inmediata de retención")

elif prob_ml >= 0.40:
    print("Monitoreo preventivo")

else:
    print("Cliente estable")